# Cluster and UI translations for 8 languages
CLUSTERS = {
    1: {
        "en": "Foundations & Small Integers",
        "de": "Grundlagen & Kleine Zahlen",
        "fr": "Fondations & Petits Entiers",
        "it": "Fondamenti & Piccoli Numeri",
        "ja": "基礎数論と小さな偶数",
        "ko": "기초 정수론과 작은 짝수",
        "zh-CN": "基础数论与小偶数",
        "zh-TW": "基礎數論與小偶數"
    },
    2: {
        "en": "Modular Arithmetic & The Power of 6",
        "de": "Modulare Arithmetik & Die Kraft der 6",
        "fr": "Arithmétique Modulaire & La Puissance de 6",
        "it": "Aritmetica Modulare & Il Potere del 6",
        "ja": "合同式（モジュロ算術）と6の倍数",
        "ko": "모듈러 연산과 6의 배수",
        "zh-CN": "模算术与6的倍数",
        "zh-TW": "模算術與6的倍數"
    },
    3: {
        "en": "Geometric, Lattice & Visual Representations",
        "de": "Geometrische, Gitter- & Visuelle Modelle",
        "fr": "Représentations Géométriques & Réseaux",
        "it": "Rappresentazioni Geometriche & Reticoli",
        "ja": "幾何・格子点・ビジュアル表現",
        "ko": "기하학, 격자점 및 시각화",
        "zh-CN": "几何、格点与可视化",
        "zh-TW": "幾何、格點與視覺化"
    },
    4: {
        "en": "The Goldbach Comet & Asymptotic Landscape",
        "de": "Der Goldbach-Komet & Asymptotische Landschaft",
        "fr": "La Comète de Goldbach & Paysage Asymptotique",
        "it": "La Cometa di Goldbach & Paesaggio Asintotico",
        "ja": "ゴールドバッハの彗星と漸近的性質",
        "ko": "골드바흐 혜성과 점근적 풍경",
        "zh-CN": "哥德巴赫彗星与渐近图景",
        "zh-TW": "哥德巴赫彗星與漸近圖景"
    },
    5: {
        "en": "Weak Goldbach & 3-Prime Partitions",
        "de": "Schwache Goldbach-Vermutung & 3-Primzahl-Partitionen",
        "fr": "Conjecture Faible de Goldbach & Partitions à 3 Premiers",
        "it": "Congettura Debole di Goldbach & Partizioni a 3 Primi",
        "ja": "弱いゴールドバッハ予想と3素数の和",
        "ko": "약한 골드바흐 추측과 3개 소수 분할",
        "zh-CN": "弱哥德巴赫猜想与三素数分割",
        "zh-TW": "弱哥德巴赫猜想與三質數分割"
    },
    6: {
        "en": "Gamified Puzzles & Detective Cases",
        "de": "Spielerische Rätsel & Mathe-Detektive",
        "fr": "Énigmes Ludiques & Enquêtes Détectives",
        "it": "Enigmi Gamificati & Casi Investigativi",
        "ja": "ゲームパズルと数学探偵",
        "ko": "게임형 퍼즐과 수학 탐정",
        "zh-CN": "游戏化谜题与数学侦探",
        "zh-TW": "遊戲化謎題與數學偵探"
    },
    7: {
        "en": "Combinatorics, Generating Functions & Probability",
        "de": "Kombinatorik, Erzeugende Funktionen & Wahrscheinlichkeit",
        "fr": "Combinatoire, Fonctions Génératrices & Probabilités",
        "it": "Combinatoria, Funzioni Generatrici & Probabilità",
        "ja": "組合せ論・母関数・確率モデル",
        "ko": "조합론, 생성함수 및 확률 모델",
        "zh-CN": "组合数学、生成函数与概率模型",
        "zh-TW": "組合數學、生成函數與機率模型"
    },
    8: {
        "en": "Historical Perspectives & Conjectures",
        "de": "Historische Perspektiven & Meilensteine",
        "fr": "Perspectives Historiques & Jalons",
        "it": "Prospettive Storiche & Pietre Miliari",
        "ja": "歴史的展望と未解決予想",
        "ko": "역사적 조망과 미해결 추측",
        "zh-CN": "历史视野、信件手稿与里程碑",
        "zh-TW": "歷史視野、信件手稿與里程碑"
    },
    9: {
        "en": "Advanced Number Theory & Modular Forms",
        "de": "Höhere Zahlentheorie & Modulformen",
        "fr": "Théorie des Nombres Avancée & Formes Modulaires",
        "it": "Teoria dei Numeri Avanzata & Forme Modulari",
        "ja": "高度整数論・楕円曲線・モジュラー形式",
        "ko": "고등 정수론, 타원곡선 및 모듈러 형식",
        "zh-CN": "高等数论、椭圆曲线与模形式",
        "zh-TW": "高等數論、橢圓曲線與模形式"
    },
    10: {
        "en": "Classroom Tools & Grand Unification",
        "de": "Klassenzimmer-Werkzeuge & Große Vereinigung",
        "fr": "Outils Pédagogiques & Grande Unification",
        "it": "Strumenti per la Classe & Grande Unificazione",
        "ja": "教室用ツールと大統一シンフォニー",
        "ko": "교실 도구와 대통합 심포니",
        "zh-CN": "课堂教学工具与大一统交响",
        "zh-TW": "課堂教學工具與大一統交響"
    }
}

UI = {
    "en": {
        "navHub": "🔬 100 Labs Hub",
        "navMainPortal": "🏠 Main Portal",
        "labPrefix": "Lab #",
        "clusterPrefix": "Cluster",
        "prev": "← Prev",
        "next": "Next →",
        "sound": "Sound",
        "soundOn": "Sound: ON",
        "soundOff": "Sound: OFF",
        "language": "Language",
        "storyTitle": "Classroom Story",
        "challengeTitle": "Student Discovery Challenge",
        "rigorTitle": "Mathematical Rigor & Formulations",
        "revealSolution": "💡 Show Solution & Explanation",
        "hideSolution": "🙈 Hide Solution",
        "hubTitle": "100 Goldbach Discovery Labs",
        "hubSub": "A monumental collection of 100 interactive, zero-dependency mathematical laboratories exploring Goldbach's Conjecture through hands-on discovery, visual proofs, physics balances, modular clocks, and modern analytic number theory.",
        "statLabs": "Discovery Labs",
        "statClusters": "Curated Clusters",
        "statChallenges": "Interactive Challenges",
        "statDeps": "External Dependencies",
        "searchPlaceholder": "Search across all 100 labs by title, theorem, prime concept, or lab number (e.g. 42, modular, comet, Euler)...",
        "filterAll": "All Clusters (100)",
        "cardExplore": "Explore Discovery Lab",
        "noResultsTitle": "No discovery labs match your search",
        "noResultsDesc": "Try searching for another keyword or reset the filter.",
        "backPortal": "← Back to Main Goldbach Portal"
    },
    "de": {
        "navHub": "🔬 100 Labore Hub",
        "navMainPortal": "🏠 Hauptportal",
        "labPrefix": "Labor #",
        "clusterPrefix": "Cluster",
        "prev": "← Zurück",
        "next": "Weiter →",
        "sound": "Ton",
        "soundOn": "Ton: AN",
        "soundOff": "Ton: AUS",
        "language": "Sprache",
        "storyTitle": "Klassenzimmer-Geschichte",
        "challengeTitle": "Entdecker-Herausforderung",
        "rigorTitle": "Mathematische Strenge & Formeln",
        "revealSolution": "💡 Lösung & Erklärung anzeigen",
        "hideSolution": "🙈 Lösung verbergen",
        "hubTitle": "100 Goldbach-Entdeckungslabore",
        "hubSub": "Eine monumentale Sammlung von 100 interaktiven mathematischen Laboren zur Erkundung der Goldbachschen Vermutung durch visuelle Beweise, Waagen, Modulo-Uhren und moderne Zahlentheorie.",
        "statLabs": "Entdeckungslabore",
        "statClusters": "Themen-Cluster",
        "statChallenges": "Interaktive Rätsel",
        "statDeps": "Externe Abhängigkeiten",
        "searchPlaceholder": "Suche in allen 100 Laboren nach Titel, Theorem, Begriff oder Labornummer...",
        "filterAll": "Alle Cluster (100)",
        "cardExplore": "Labor erkunden",
        "noResultsTitle": "Keine Labore gefunden",
        "noResultsDesc": "Versuche einen anderen Suchbegriff oder setze den Filter zurück.",
        "backPortal": "← Zurück zum Hauptportal"
    },
    "fr": {
        "navHub": "🔬 Hub des 100 Labs",
        "navMainPortal": "🏠 Portail Principal",
        "labPrefix": "Lab #",
        "clusterPrefix": "Groupe",
        "prev": "← Précédent",
        "next": "Suivant →",
        "sound": "Son",
        "soundOn": "Son: ON",
        "soundOff": "Son: OFF",
        "language": "Langue",
        "storyTitle": "Histoire Pédagogique",
        "challengeTitle": "Défi Découverte Élève",
        "rigorTitle": "Rigueur Mathématique & Formules",
        "revealSolution": "💡 Afficher la solution",
        "hideSolution": "🙈 Masquer la solution",
        "hubTitle": "100 Laboratoires de Découverte de Goldbach",
        "hubSub": "Une collection monumentale de 100 laboratoires mathématiques interactifs explorant la conjecture de Goldbach par des balances physiques, horloges modulaires et la théorie analytique des nombres.",
        "statLabs": "Laboratoires",
        "statClusters": "Groupes Thématiques",
        "statChallenges": "Défis Interactifs",
        "statDeps": "Dépendances Externes",
        "searchPlaceholder": "Rechercher parmi les 100 labs par titre, théorème, concept ou numéro...",
        "filterAll": "Tous les groupes (100)",
        "cardExplore": "Explorer le lab",
        "noResultsTitle": "Aucun laboratoire trouvé",
        "noResultsDesc": "Essayez un autre mot-clé ou réinitialisez le filtre.",
        "backPortal": "← Retour au Portail Principal"
    },
    "it": {
        "navHub": "🔬 Hub dei 100 Lab",
        "navMainPortal": "🏠 Portale Principale",
        "labPrefix": "Lab #",
        "clusterPrefix": "Cluster",
        "prev": "← Prec",
        "next": "Succ →",
        "sound": "Audio",
        "soundOn": "Audio: ON",
        "soundOff": "Audio: OFF",
        "language": "Lingua",
        "storyTitle": "Storia per la Classe",
        "challengeTitle": "Sfida di Scoperta per Studenti",
        "rigorTitle": "Rigore Matematico & Formule",
        "revealSolution": "💡 Mostra soluzione e spiegazione",
        "hideSolution": "🙈 Nascondi soluzione",
        "hubTitle": "100 Laboratori di Scoperta di Goldbach",
        "hubSub": "Una raccolta monumentale di 100 laboratori matematici interattivi per esplorare la congettura di Goldbach attraverso bilance fisiche, orologi modulari e teoria analitica dei numeri.",
        "statLabs": "Laboratori",
        "statClusters": "Cluster Curati",
        "statChallenges": "Sfide Interattive",
        "statDeps": "Dipendenze Esterne",
        "searchPlaceholder": "Cerca tra tutti i 100 laboratori per titolo, teorema, concetto o numero...",
        "filterAll": "Tutti i cluster (100)",
        "cardExplore": "Esplora laboratorio",
        "noResultsTitle": "Nessun laboratorio trovato",
        "noResultsDesc": "Prova un altro termine o reimposta il filtro.",
        "backPortal": "← Torna al Portale Principale"
    },
    "ja": {
        "navHub": "🔬 100ラボ ハブ",
        "navMainPortal": "🏠 メインポータル",
        "labPrefix": "ラボ #",
        "clusterPrefix": "クラスター",
        "prev": "← 前へ",
        "next": "次へ →",
        "sound": "音声",
        "soundOn": "音声: ON",
        "soundOff": "音声: OFF",
        "language": "言語",
        "storyTitle": "教室のストーリー",
        "challengeTitle": "生徒の発見チャレンジ",
        "rigorTitle": "厳密な数学的定式化",
        "revealSolution": "💡 解答と解説を表示",
        "hideSolution": "🙈 解答を隠す",
        "hubTitle": "ゴールドバッハ 100の探究ラボ",
        "hubSub": "天秤、モジュロ時計、彗星グラフ、3次元幾何学、現代解析的整数論を通じてゴールドバッハ予想を探究する、100の完全インタラクティブ数学ラボです。",
        "statLabs": "探究ラボ数",
        "statClusters": "厳選クラスター",
        "statChallenges": "体験チャレンジ",
        "statDeps": "外部依存ライブラリ",
        "searchPlaceholder": "タイトル、定理、素数の概念、またはラボ番号で検索...",
        "filterAll": "全クラスター (100)",
        "cardExplore": "実験室に入る",
        "noResultsTitle": "該当するラボが見つかりません",
        "noResultsDesc": "別のキーワードで検索するか、フィルターをリセットしてください。",
        "backPortal": "← メインポータルに戻る"
    },
    "ko": {
        "navHub": "🔬 100개 랩 허브",
        "navMainPortal": "🏠 메인 포털",
        "labPrefix": "실험실 #",
        "clusterPrefix": "클러스터",
        "prev": "← 이전",
        "next": "다음 →",
        "sound": "소리",
        "soundOn": "소리: ON",
        "soundOff": "소리: OFF",
        "language": "언어",
        "storyTitle": "교실 이야기",
        "challengeTitle": "학생 발견 챌린지",
        "rigorTitle": "엄밀한 수학적 정의와 공식",
        "revealSolution": "💡 해답 및 해설 보기",
        "hideSolution": "🙈 해답 숨기기",
        "hubTitle": "골드바흐 100대 탐구 실험실",
        "hubSub": "물리적 저울, 모듈러 시계, 혜성 그래프, 3D 기하학 및 현대 해석적 정수론을 통해 골드바흐 추측을 탐구하는 100개의 무설치 인터랙티브 수학 실험실입니다.",
        "statLabs": "탐구 실험실",
        "statClusters": "테마 클러스터",
        "statChallenges": "인터랙티브 챌린지",
        "statDeps": "외부 종속성",
        "searchPlaceholder": "제목, 정리, 소수 개념 또는 번호로 100개 실험실 검색...",
        "filterAll": "전체 클러스터 (100)",
        "cardExplore": "실험실 탐색하기",
        "noResultsTitle": "검색 결과가 없습니다",
        "noResultsDesc": "다른 키워드로 검색하거나 필터를 재설정하세요.",
        "backPortal": "← 메인 포털로 돌아가기"
    },
    "zh-CN": {
        "navHub": "🔬 100探索实验室",
        "navMainPortal": "🏠 返回主站",
        "labPrefix": "实验 #",
        "clusterPrefix": "集群",
        "prev": "← 上一个",
        "next": "下一个 →",
        "sound": "声音",
        "soundOn": "声音: 开启",
        "soundOff": "声音: 静音",
        "language": "语言",
        "storyTitle": "课堂故事与直觉",
        "challengeTitle": "学生探索挑战",
        "rigorTitle": "严谨数学定义与公式",
        "revealSolution": "💡 查看解析与答案",
        "hideSolution": "🙈 收起解析",
        "hubTitle": "100个哥德巴赫探索实验室",
        "hubSub": "涵盖物理天平、模6时钟、彗星图景、3D几何单形、游戏谜题到现代解析数论的100个完全独立、零外部依赖的交互式数学探索实验室。",
        "statLabs": "探索实验室",
        "statClusters": "精选数学集群",
        "statChallenges": "互动探索挑战",
        "statDeps": "外部网络依赖",
        "searchPlaceholder": "按实验标题、数学定理、素数概念或序号搜索全部100个实验（如 42、模6、彗星、欧拉）...",
        "filterAll": "全部集群 (100)",
        "cardExplore": "进入实验室",
        "noResultsTitle": "未找到匹配的实验室",
        "noResultsDesc": "请尝试其他关键词或重置集群筛选。",
        "backPortal": "← 返回主站门户"
    },
    "zh-TW": {
        "navHub": "🔬 100探索實驗室",
        "navMainPortal": "🏠 返回主站",
        "labPrefix": "實驗 #",
        "clusterPrefix": "集群",
        "prev": "← 上一個",
        "next": "下一個 →",
        "sound": "聲音",
        "soundOn": "聲音: 開啟",
        "soundOff": "聲音: 靜音",
        "language": "語言",
        "storyTitle": "課堂故事與直覺",
        "challengeTitle": "學生探索挑戰",
        "rigorTitle": "嚴謹數學定義與公式",
        "revealSolution": "💡 查看解析與答案",
        "hideSolution": "🙈 收起解析",
        "hubTitle": "100個哥德巴赫探索實驗室",
        "hubSub": "涵蓋物理天平、模6時鐘、彗星圖景、3D幾何單形、遊戲謎題到現代解析數論的100個完全獨立、零外部依賴的互動式數學探索實驗室。",
        "statLabs": "探索實驗室",
        "statClusters": "精選數學集群",
        "statChallenges": "互動探索挑戰",
        "statDeps": "外部網絡依賴",
        "searchPlaceholder": "按實驗標題、數學定理、質數概念或序號搜尋全部100個實驗（如 42、模6、彗星、歐拉）...",
        "filterAll": "全部集群 (100)",
        "cardExplore": "進入實驗室",
        "noResultsTitle": "未找到匹配的實驗室",
        "noResultsDesc": "請嘗試其他關鍵字或重設集群篩選。",
        "backPortal": "← 返回主站門戶"
    }
}
